version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: pcart
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    healthcheck:
      test: 
        - "CMD"
        - "mongosh"
        - "--eval"
        - "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://admin:password@mongodb:27017/pcart?authSource=admin
      JWT_SECRET: your_jwt_secret_key_here
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000" # Use port 3000 for React dev server
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - server
    restart: unless-stopped
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongodb_data:

